allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  "@tailwindcss/oxide": true
  "esbuild": true
  "sharp": true
  "workerd": true

"overrides":
  "vite": 'catalog:'
  "vitest": 'catalog:'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
  vite-plus: ^0.2.1
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
